// Derived from csdl by Albie Spriddell. See libtorrentsharp/NOTICE for attribution.
// csdl - a cross-platform libtorrent wrapper for .NET
// Licensed under Apache-2.0 - see the license file for more information

namespace LibtorrentSharp.Enums;

/// <summary>
/// Discriminator values for alert dispatching. Each value identifies a concrete
/// <see cref="LibtorrentSharp.Alerts.Alert"/> subtype returned by the alert pump.
/// </summary>
public enum AlertType
{
    Generic = 0,
    TorrentStatus = 1,
    ClientPerformance = 2,
    Peer = 3,
    TorrentRemoved = 4,
    ResumeDataReady = 5,
    DhtStats = 6,
    DhtPut = 7,
    DhtImmutableItem = 8,
    DhtMutableItem = 9,
    SessionStats = 10,
    ListenSucceeded = 11,
    ListenFailed = 12,
    TorrentPaused = 13,
    TorrentResumed = 14,
    TorrentFinished = 15,
    TorrentChecked = 16,
    StorageMoved = 17,
    StorageMovedFailed = 18,
    TrackerReply = 19,
    TrackerError = 20,
    ScrapeReply = 21,
    ScrapeFailed = 22,
    TrackerAnnounce = 23,
    TrackerWarning = 24,
    FileRenamed = 25,
    FileRenameFailed = 26,
    FastresumeRejected = 27,
    SaveResumeDataFailed = 28,
    TorrentDeleted = 29,
    TorrentDeleteFailed = 30,
    MetadataReceived = 31,
    MetadataFailed = 32,
    TorrentError = 33,
    FileError = 34,
    UdpError = 35,
    SessionError = 36,
    DhtError = 37,
    LsdError = 38,
    HashFailed = 39,
    ExternalIp = 40,
    Portmap = 41,
    PortmapError = 42,
    DhtBootstrap = 43,
    DhtReply = 44,
    Trackerid = 45,
    CacheFlushed = 46,
    DhtAnnounce = 47,
    DhtGetPeers = 48,
    DhtOutgoingGetPeers = 49,
    AddTorrent = 50,
    TorrentNeedCert = 51,
    TorrentConflict = 52,
    FileCompleted = 53,
    PieceFinished = 54,
    UrlSeed = 55,
    BlockFinished = 56,
    BlockUploaded = 57,
    PeerBlocked = 58,
    IncomingConnection = 59,
    BlockTimeout = 60,
    BlockDownloading = 61,
    UnwantedBlock = 62,
    Socks5 = 63,
    I2p = 64,
    TorrentLog = 65,
    Log = 66,
    DhtLog = 67
}